schema.json
=> fix: metaschema version one

schema.json
=> fix: use https for json-schema 7 links

schema.json
=> fix(methodObject): dont allow additionalProperties

schema.json
=> fix(servers): dont allow additional props

schema.json
=> feat: enum openrpc version

schema.json
=> fix: replace required

schema.json
=> fix: add $ref to meta schema

package-lock.json, package.json, schema.json
fixes #47, fixes #44 
rel https://github.com/open-rpc/examples/pull/37
=> feat: add method.errors support

schema.json
=> fix: add 1.0.0 to openrpc enum strings

schema.json
=> docs: add format for of termsOfService

schema.json
=> fix: name must exist

bin/build.js, package-lock.json, package.json
This fixes the current issue of names breaking type generation.
=> feat: switch to using quicktype to generate types

schema.json
=> allow externalDocs on root

schema.json
=> fix(methodObject): add 'externalDocs' to properties 

schema.json
=> fix(methodObject): add servers property 

schema.json
=> fix(contentDescriptorObject): add deprecated property

meta_schema.go, package-lock.json, package.json
Run 'npm run build' to regenerate generate meta_schema.go
Signed-off-by: meows <b5c6@protonmail.com>
https://github.com/etclabscore/json-schema-to-types/releases/tag/1.11.2
=> feat(json-schema-to-types): bump to v1.11.2

schema.json, src/test.ts
=> fix: allow methods array to have refs

schema.json
=> fix: make result optional for notifications

schema.json
=> fix: give $schema a title

package-lock.json, package.json
=> fix: big bump, my lovely lady bumps
